name: Master Workflow - Build and deploy to production
on:
  pull_request:
    branches: [ main ]
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [ "event-triggered-by-jira" ]
  
jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps:
#    - name: Comment on issue
#      uses: atlassian/gajira-comment@master
#      with:
#        issue: UTX-1
#        comment: ${{ github.event.pusher.name }} pushed to repository- ${{ github.event.repository.full_name }}
   
#    - name: 'Assert Branch Naming Convention'
#      uses: deepakputhraya/action-branch-name@master
#      with:
#        regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This example enforces grouping
#        allowed_prefixes: 'feature,stable,fix' # All branches should start with the given prefix
#        ignore: master,develop # Ignore exactly matching branch names from convention
#        min_length: 5 # Min length of the branch name
#        max_length: 20 # Max length of the branch name
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    
    - name: Print Services
      id: jira_release_services
      run: |
        output=${{ github.event.client_payload.services }}
        echo "Services are ${{ github.event.client_payload.services }}"
        echo "${output}}"
        

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed

#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install json
    
    - name: Check JIRA Status
      id: jira_create_manifest
      run: |
        output=$(python jira_create_manifest.py ${{ github.event.client_payload.services }})
        echo "${output}}"
        echo "::set-output name=manifest_json::$output"
        
    - name: Checkout Manifest Repo
      uses: actions/checkout@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'vibhorchhabra321/service-manifest'
    - name: create-Manifest-File
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "manifest.json"
        json: ${{ steps.jira_create_manifest.outputs.manifest_json }}
        dir: "manifest-data/"
    - name: Commit files
      run: |
        git config --local user.email "vibhor.rc@gmail.com"
        git config --local user.name "vibhorchhabra321"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'vibhorchhabra321/service-manifest'
        branch: "develop"
    
