name: Master Workflow - Build and deploy to production
on: [pull_request]
  
jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Parse Jira Keys from Commit
      id: jira_keys
      if: always()
      uses: HighwayThree/jira-extract-issue-keys@master
      with:
        is-pull-request: ${{ github.event_name == 'pull_request' }}
        parse-all-commits: ${{ github.event_name == 'push' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: "${{ steps.jira_keys.outputs.jira-keys }}"
        comment: ${{ github.event.pusher.name }} pushed to repository - ${{ github.event.repository.full_name }}
