name: Commit Checker

# Run on push to any branch
on: [push]

jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: 'UTX-[0-9]+'
        flags: 'gm'
        error: 'Your first line has to contain a commit type like "UTX-1".'
    
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: "https://uneritx.atlassian.net"
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: Find in commit messages
      id: jira_issue
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits
    
    - name: Echo JIRA Issue
      run: |
        echo " ${{steps.jira_issue.outputs.Issue}}

  JIRA_Validator:
    runs-on: ubuntu-latest
    needs: Commit_Checker
    
    steps:
    - name: Echo JIRA ID
    
      run: |
        echo ${{needs.jobs.Commit_Checker.outputs.Issue}} 
  
  
