name: Master Workflow - Build and deploy to production
on: [pull_request]
  
jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps:       
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: UTX-1
        comment: ${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}
