name: Master Workflow - JIRA Update
on: [pull_request]
  
jobs:
  JIRA-Status-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check JIRA Issue in PR Title & Description
        uses: fgiuliani/jira-issue-key-checker@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          jira-prefix: "UTX"
          
      - name: Parse Jira Keys from Commit
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: "https://uneritx.atlassian.net"
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      
      - name: Comment on issue
        uses: atlassian/gajira-comment@master
        with:
          issue: "${{ steps.jira_keys.outputs.jira-keys }}"
          comment: ${{ github.event.pusher.name }} Pull Request Opened for - ${{ github.event.repository.full_name }} ${{ github.head_ref }} branch at ${{ steps.date.outputs.date }}  
