name: Master Workflow - Build and deploy to production
on: [pull_request]
  
jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Check JIRA Issue in PR Title & Description
      uses: fgiuliani/jira-issue-key-checker@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        jira-prefix: 'UTX'
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: UTX-1
        comment: ${{ github.event.pusher.name }} pushed to repository - ${{ github.event.repository.full_name }}
