name: Commit Checker

# Run on push to any branch
on: [push]

jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: '${{ github.event.pull_request.base.ref }}'
    
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: "https://uneritx.atlassian.net"
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits
