name: build-on-merge

on:
  push:
    branches: ["main"]

jobs:
  build-on-merge:
    runs-on: ubuntu-latest
    
    steps:   
    - name: Merge Author
      if: startsWith(github.event.head_commit.message, 'Merge pull request')
      run: |
        echo "${{ github.event.head_commit.author.email }}"
